default_platform(:ios)

platform :ios do
  desc "Uploader vers TestFlight"
  lane :upload do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false
    )

    upload_to_testflight(
      ipa: "./build/PrivilegeClub.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
