lane :upload do
  app_store_connect_api_key(
    key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
    issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
    key_filepath: "AuthKey.p8"
  )

  upload_to_testflight(
    ipa: "./build/PrivilegeClub.ipa",
    skip_waiting_for_build_processing: true
  )
end
