default_platform(:ios)

platform :ios do
  desc "Upload build to TestFlight"
  lane :upload do
    # Lecture des variables d'environnement injectées par GitHub
    api_key_path = ENV["APP_STORE_CONNECT_API_KEY_PATH"]
    api_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
    issuer_id = ENV["APP_STORE_CONNECT_API_ISSUER_ID"]

    # Authentification App Store Connect API
    app_store_connect_api_key(
      key_id: api_key_id,
      issuer_id: issuer_id,
      key_filepath: api_key_path
    )

    # Envoi de l'IPA à TestFlight
    upload_to_testflight(
      ipa: "./build/PrivilegeClub.ipa",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false
    )
  end
end
